{{- if .Values.airline.ingress.enabled }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0 <1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "airline.fullname" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "airline.name" . }}
    helm.sh/chart: {{ include "airline.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.airline.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.airline.ingress.tls_enabled }}
  tls:
  {{- range .Values.airline.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- $serviceName := include "airline.fullname" . -}}
  {{- range .Values.airline.ingress.hosts }}
  - host: {{ .host.domain | quote }}
    http:
      paths:
      - path: {{ .host.path }}
        {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
        pathType: {{ .host.pathType }}
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ $serviceName }}
            port:
              name: {{ .host.port }}
          {{- else }}
          serviceName: {{ $serviceName }}
          servicePort: {{ .host.port }}
          {{- end }}
  {{- end }}
{{- end }}
