apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "airline.fullname" . }}-secret
data:
  SQL_PASSWORD: {{ tpl .Values.airline.sql.password . | b64enc | quote }}
  SMTP_PASSWORD: {{ tpl .Values.airline.smtp.password . | b64enc | quote }}
